// Mapping: nom GeoJSON (anglais) -> nom français (tel que stocké dans user_zones / CONTINENTS)
// Les pays non listés ici restent grisés (petits territoires sans polygone dans le GeoJSON).
export const GEOJSON_TO_FRENCH: Record<string, string> = {
  // Amérique du Nord
  'Canada': 'Canada',
  'United States': 'États-Unis',
  'Mexico': 'Mexique',
  'Bermuda': 'Bermudes',
  'Greenland': 'Groenland',
  // Amérique Centrale / Caraïbes
  'Belize': 'Belize',
  'Costa Rica': 'Costa Rica',
  'El Salvador': 'Salvador',
  'Guatemala': 'Guatemala',
  'Honduras': 'Honduras',
  'Nicaragua': 'Nicaragua',
  'Panama': 'Panama',
  'Bahamas': 'Bahamas',
  'Cuba': 'Cuba',
  'Dominican Rep.': 'Republique dominicaine',
  'Haiti': 'Haïti',
  'Jamaica': 'Jamaïque',
  'Trinidad and Tobago': 'Trinite-et-Tobago',
  // Amérique du Sud
  'Argentina': 'Argentine',
  'Bolivia': 'Bolivie',
  'Brazil': 'Brésil',
  'Chile': 'Chili',
  'Colombia': 'Colombie',
  'Ecuador': 'Équateur',
  'Guyana': 'Guyana',
  'Paraguay': 'Paraguay',
  'Peru': 'Pérou',
  'Suriname': 'Suriname',
  'Uruguay': 'Uruguay',
  'Venezuela': 'Venezuela',
  // Océanie
  'Australia': 'Australie',
  'Fiji': 'Fidji',
  'Vanuatu': 'Vanuatu',
  'New Zealand': 'Nouvelle-Zelande',
  'Papua New Guinea': 'Papouasie-Nouvelle-Guinee',
  'Solomon Is.': 'Salomon',
  // Europe
  'Albania': 'Albanie',
  'Germany': 'Allemagne',
  'Austria': 'Autriche',
  'Belgium': 'Belgique',
  'Belarus': 'Bielorussie',
  'Bosnia and Herz.': 'Bosnie-Herzegovine',
  'Bulgaria': 'Bulgarie',
  'Cyprus': 'Chypre',
  'Croatia': 'Croatie',
  'Denmark': 'Danemark',
  'Spain': 'Espagne',
  'Estonia': 'Estonie',
  'Finland': 'Finlande',
  'France': 'France',
  'Greece': 'Grèce',
  'Hungary': 'Hongrie',
  'Ireland': 'Irlande',
  'Iceland': 'Islande',
  'Italy': 'Italie',
  'Kosovo': 'Kosovo',
  'Latvia': 'Lettonie',
  'Lithuania': 'Lituanie',
  'Luxembourg': 'Luxembourg',
  'Macedonia': 'Macedoine du Nord',
  'Moldova': 'Moldavie',
  'Montenegro': 'Monténégro',
  'Norway': 'Norvege',
  'Netherlands': 'Pays-Bas',
  'Poland': 'Pologne',
  'Portugal': 'Portugal',
  'Czech Rep.': 'République tchèque',
  'Romania': 'Roumanie',
  'United Kingdom': 'Royaume-Uni',
  'Serbia': 'Serbie',
  'Slovakia': 'Slovaquie',
  'Slovenia': 'Slovenie',
  'Sweden': 'Suède',
  'Switzerland': 'Suisse',
  'Ukraine': 'Ukraine',
  // Moyen-Orient
  'Saudi Arabia': 'Arabie saoudite',
  'Bahrain': 'Bahreïn',
  'United Arab Emirates': 'Émirats arabes unis',
  'Iran': 'Iran',
  'Iraq': 'Irak',
  'Israel': 'Israël',
  'Jordan': 'Jordanie',
  'Kuwait': 'Koweït',
  'Lebanon': 'Liban',
  'Oman': 'Oman',
  'Qatar': 'Qatar',
  'Syria': 'Syrie',
  'Yemen': 'Yémen',
  'West Bank': 'Palestine',
  // Asie
  'Afghanistan': 'Afghanistan',
  'Armenia': 'Arménie',
  'Azerbaijan': 'Azerbaïdjan',
  'Bangladesh': 'Bangladesh',
  'Bhutan': 'Bhoutan',
  'Myanmar': 'Birmanie (Myanmar)',
  'Brunei': 'Brunei',
  'Cambodia': 'Cambodge',
  'China': 'Chine',
  'North Korea': 'Coree du Nord',
  'South Korea': 'Coree du Sud',
  'Georgia': 'Géorgie',
  'India': 'Inde',
  'Indonesia': 'Indonésie',
  'Japan': 'Japon',
  'Kazakhstan': 'Kazakhstan',
  'Kyrgyzstan': 'Kirghizistan',
  'Laos': 'Laos',
  'Malaysia': 'Malaisie',
  'Mongolia': 'Mongolie',
  'Nepal': 'Népal',
  'Uzbekistan': 'Ouzbékistan',
  'Pakistan': 'Pakistan',
  'Philippines': 'Philippines',
  'Russia': 'Russie',
  'Sri Lanka': 'Sri Lanka',
  'Tajikistan': 'Tadjikistan',
  'Taiwan': 'Taïwan',
  'Thailand': 'Thaïlande',
  'Timor-Leste': 'Timor oriental',
  'Turkey': 'Turquie',
  'Turkmenistan': 'Turkmenistan',
  'Vietnam': 'Viêt Nam',
  // Afrique
  'South Africa': 'Afrique du Sud',
  'Algeria': 'Algérie',
  'Angola': 'Angola',
  'Benin': 'Bénin',
  'Botswana': 'Botswana',
  'Burkina Faso': 'Burkina Faso',
  'Burundi': 'Burundi',
  'Cameroon': 'Cameroun',
  'Chad': 'Tchad',
  "Côte d'Ivoire": "Côte d'Ivoire",
  'Dem. Rep. Congo': 'Congo (RDC / Kinshasa)',
  'Congo': 'Congo (Brazzaville)',
  'Djibouti': 'Djibouti',
  'Egypt': 'Égypte',
  'Eritrea': 'Érythrée',
  'Swaziland': 'Eswatini (ex-Swaziland)',
  'Ethiopia': 'Éthiopie',
  'Gabon': 'Gabon',
  'Gambia': 'Gambie',
  'Ghana': 'Ghana',
  'Guinea': 'Guinee',
  'Eq. Guinea': 'Guinée équatoriale',
  'Guinea Bissau': 'Guinée-Bissau',
  'Kenya': 'Kenya',
  'Lesotho': 'Lesotho',
  'Liberia': 'Liberia',
  'Libya': 'Libye',
  'Madagascar': 'Madagascar',
  'Malawi': 'Malawi',
  'Mali': 'Mali',
  'Morocco': 'Maroc',
  'Mauritania': 'Mauritanie',
  'Mozambique': 'Mozambique',
  'Namibia': 'Namibie',
  'Niger': 'Niger',
  'Nigeria': 'Nigeria',
  'Uganda': 'Ouganda',
  'Rwanda': 'Rwanda',
  'Senegal': 'Sénégal',
  'Sierra Leone': 'Sierra Leone',
  'Somalia': 'Somalie',
  'Sudan': 'Soudan',
  'South Sudan': 'Soudan du Sud',
  'Tanzania': 'Tanzanie',
  'Togo': 'Togo',
  'Tunisia': 'Tunisie',
  'Zambia': 'Zambie',
  'Zimbabwe': 'Zimbabwe',
};